import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import ComponentWithFetch from 'components/ComponentWithFetch';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.row}>
          <ComponentWithFetch crud={[10, 10, 10, 10]} />
          <ComponentWithFetch crud={[2, 10, 10, 10]} />
          <ComponentWithFetch crud={[3, 10, 10, 10]} />
          <ComponentWithFetch crud={[4, 10, 10, 10]} />
        </div>
        <div className={styles.row}>
          <ComponentWithFetch crud={[10, 10, 10, 10]} />
          <ComponentWithFetch crud={[10, 2, 10, 10]} />
          <ComponentWithFetch crud={[10, 3, 10, 10]} />
          <ComponentWithFetch crud={[10, 4, 10, 10]} />
        </div>
        <div className={styles.row}>
          <ComponentWithFetch crud={[10, 10, 10, 10]} />
          <ComponentWithFetch crud={[10, 10, 2, 10]} />
          <ComponentWithFetch crud={[10, 10, 3, 10]} />
          <ComponentWithFetch crud={[10, 10, 4, 10]} />
        </div>
        <div className={styles.row}>
          <ComponentWithFetch crud={[10, 10, 10, 10]} />
          <ComponentWithFetch crud={[10, 10, 10, 2]} />
          <ComponentWithFetch crud={[10, 10, 10, 3]} />
          <ComponentWithFetch crud={[10, 10, 10, 4]} />
        </div>
        <div className={styles.row}>
          <ComponentWithFetch crud={[10, 2, 10, 10]} />
          <ComponentWithFetch crud={[2, 2, 10, 10]} />
          <ComponentWithFetch crud={[3, 2, 10, 10]} />
          <ComponentWithFetch crud={[4, 2, 10, 10]} />
        </div>
        <div className={styles.row}>
          <ComponentWithFetch crud={[2, 10, 10, 10]} />
          <ComponentWithFetch crud={[2, 2, 10, 10]} />
          <ComponentWithFetch crud={[2, 3, 10, 10]} />
          <ComponentWithFetch crud={[2, 4, 10, 10]} />
        </div>
        <div className={styles.row}>
          <ComponentWithFetch crud={[10, 10, 10, 2]} />
          <ComponentWithFetch crud={[10, 10, 2, 2]} />
          <ComponentWithFetch crud={[10, 10, 3, 2]} />
          <ComponentWithFetch crud={[10, 10, 4, 2]} />
        </div>
        <div className={styles.row}>
          <ComponentWithFetch crud={[10, 2, 10, 10]} />
          <ComponentWithFetch crud={[10, 2, 10, 2]} />
          <ComponentWithFetch crud={[10, 2, 10, 3]} />
          <ComponentWithFetch crud={[10, 2, 10, 4]} />
        </div>
      </main>
    </>
  )
}
