# Generated by Django 5.0.1 on 2024-01-14 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='article',
        ),
        migrations.AddField(
            model_name='reaction',
            name='comment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='blog.comment'),
            preserve_default=False,
        ),
    ]
