# Generated by Django 3.0.6 on 2020-05-05 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('author_field_1', models.CharField(max_length=255)),
                ('author_field_2', models.CharField(max_length=255)),
                ('author_field_3', models.CharField(max_length=255)),
                ('author_field_4', models.CharField(max_length=255)),
                ('author_field_5', models.CharField(max_length=255)),
                ('author_field_6', models.CharField(max_length=255)),
                ('author_field_7', models.CharField(max_length=255)),
                ('author_field_8', models.CharField(max_length=255)),
                ('author_field_9', models.CharField(max_length=255)),
                ('author_field_10', models.CharField(max_length=255)),
                ('author_field_11', models.CharField(max_length=255)),
                ('author_field_12', models.CharField(max_length=255)),
                ('author_field_13', models.CharField(max_length=255)),
                ('author_field_14', models.CharField(max_length=255)),
                ('author_field_15', models.CharField(max_length=255)),
                ('author_field_16', models.CharField(max_length=255)),
                ('author_field_17', models.CharField(max_length=255)),
                ('author_field_18', models.CharField(max_length=255)),
                ('author_field_19', models.CharField(max_length=255)),
                ('author_field_20', models.CharField(max_length=255)),
                ('author_field_21', models.CharField(max_length=255)),
                ('author_field_22', models.CharField(max_length=255)),
                ('author_field_23', models.CharField(max_length=255)),
                ('author_field_24', models.CharField(max_length=255)),
                ('author_field_25', models.CharField(max_length=255)),
                ('author_field_26', models.CharField(max_length=255)),
                ('author_field_27', models.CharField(max_length=255)),
                ('author_field_28', models.CharField(max_length=255)),
                ('author_field_29', models.CharField(max_length=255)),
                ('author_field_30', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('article_field_1', models.CharField(max_length=255)),
                ('article_field_2', models.CharField(max_length=255)),
                ('article_field_3', models.CharField(max_length=255)),
                ('article_field_4', models.CharField(max_length=255)),
                ('article_field_5', models.CharField(max_length=255)),
                ('article_field_6', models.CharField(max_length=255)),
                ('article_field_7', models.CharField(max_length=255)),
                ('article_field_8', models.CharField(max_length=255)),
                ('article_field_9', models.CharField(max_length=255)),
                ('article_field_10', models.CharField(max_length=255)),
                ('article_field_11', models.CharField(max_length=255)),
                ('article_field_12', models.CharField(max_length=255)),
                ('article_field_13', models.CharField(max_length=255)),
                ('article_field_14', models.CharField(max_length=255)),
                ('article_field_15', models.CharField(max_length=255)),
                ('article_field_16', models.CharField(max_length=255)),
                ('article_field_17', models.CharField(max_length=255)),
                ('article_field_18', models.CharField(max_length=255)),
                ('article_field_19', models.CharField(max_length=255)),
                ('article_field_20', models.CharField(max_length=255)),
                ('article_field_21', models.CharField(max_length=255)),
                ('article_field_22', models.CharField(max_length=255)),
                ('article_field_23', models.CharField(max_length=255)),
                ('article_field_24', models.CharField(max_length=255)),
                ('article_field_25', models.CharField(max_length=255)),
                ('article_field_26', models.CharField(max_length=255)),
                ('article_field_27', models.CharField(max_length=255)),
                ('article_field_28', models.CharField(max_length=255)),
                ('article_field_29', models.CharField(max_length=255)),
                ('article_field_30', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='dashboard.Author')),
            ],
        ),
    ]
