# Generated by Django 3.0.6 on 2020-05-19 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_invoice_invoiceitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='data',
            new_name='date',
        ),
    ]
