# Generated by Django 3.0.6 on 2020-05-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_invoiceitem_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeavyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dec_field_1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dec_field_2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dec_field_3', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dec_field_4', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dec_field_5', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dec_field_6', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dec_field_7', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dec_field_8', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dec_field_9', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dec_field_10', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dec_field_11', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dec_field_12', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dec_field_13', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dec_field_14', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dec_field_15', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dec_field_16', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dec_field_17', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dec_field_18', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dec_field_19', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dec_field_20', models.DecimalField(decimal_places=2, max_digits=10)),
                ('text_field_1', models.TextField()),
                ('text_field_2', models.TextField()),
                ('text_field_3', models.TextField()),
                ('text_field_4', models.TextField()),
                ('text_field_5', models.TextField()),
                ('text_field_6', models.TextField()),
                ('text_field_7', models.TextField()),
                ('text_field_8', models.TextField()),
                ('text_field_9', models.TextField()),
                ('text_field_10', models.TextField()),
                ('text_field_11', models.TextField()),
                ('text_field_12', models.TextField()),
                ('text_field_13', models.TextField()),
                ('text_field_14', models.TextField()),
                ('text_field_15', models.TextField()),
                ('text_field_16', models.TextField()),
                ('text_field_17', models.TextField()),
                ('text_field_18', models.TextField()),
                ('text_field_19', models.TextField()),
                ('text_field_20', models.TextField()),
            ],
        ),
    ]
